name: market_app
description: "market app by flutter"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^9.0.3
  flutter_riverpod: ^2.3.6

  google_sign_in: ^6.1.4

  image_picker: ^0.8.9
  intl: ^0.18.1
  dots_indicator: ^3.0.0

  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  flutter_image_compress: ^2.0.3

  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  firebase_storage: ^11.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.1

flutter:


  uses-material-design: true
  assets:
    - assets/
    - assets/images/



